apiVersion: v1
kind: Secret
metadata:
  name: lakehouse-secrets
  namespace: lakehouse
type: Opaque
stringData:
  MINIO_ROOT_USER: REPLACE_WITH_MINIO_ACCESS_KEY
  MINIO_ROOT_PASSWORD: REPLACE_WITH_MINIO_SECRET_KEY
  POSTGRES_USER: REPLACE_WITH_POSTGRES_USER
  POSTGRES_PASSWORD: REPLACE_WITH_POSTGRES_PASSWORD
  POSTGRES_DB: metastore_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
  namespace: lakehouse
data:
  hive-site.xml: |
    <configuration>
        <property>
            <name>metastore.thrift.uris</name>
            <value>thrift://hive-metastore:9083</value>
            <description>Thrift URI for remote metastore.</description>
        </property>
        <property>
            <name>metastore.expression.proxy</name>
            <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
        </property>
        <property>
            <name>hive.metastore.event.db.notification.api.auth</name>
            <value>false</value>
        </property>
        <property>
            <name>fs.defaultFS</name>
            <value>s3a://wba</value>
        </property>
        <property>
            <name>metastore.warehouse.dir</name>
            <value>s3a://wba/warehouse/</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>org.postgresql.Driver</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:postgresql://postgres:5432/metastore_db</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>${env:POSTGRES_USER}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>${env:POSTGRES_PASSWORD}</value>
        </property>
        <property>
            <name>fs.s3a.access.key</name>
            <value>${env:MINIO_ROOT_USER}</value>
        </property>
        <property>
            <name>fs.s3a.secret.key</name>
            <value>${env:MINIO_ROOT_PASSWORD}</value>
        </property>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>http://minio:9000</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
    </configuration>
  entrypoint.sh: |
    #!/bin/sh

    set -x

    : ${DB_DRIVER:=derby}

    SKIP_SCHEMA_INIT="${IS_RESUME:-false}"

    initialize_hive() {
      if "$HIVE_HOME"/bin/schematool -dbType "$DB_DRIVER" -initSchema; then
        echo "Initialized schema successfully.."
      else
        echo "Schema initialization failed!"
        exit 1
      fi
    }

    export HIVE_CONF_DIR="$HIVE_HOME/conf"
    if [ -d "${HIVE_CUSTOM_CONF_DIR:-}" ]; then
      find "${HIVE_CUSTOM_CONF_DIR}" -type f -exec ln -sfn {} "${HIVE_CONF_DIR}"/ \;
      export HADOOP_CONF_DIR="$HIVE_CONF_DIR"
      export TEZ_CONF_DIR="$HIVE_CONF_DIR"
    fi

    export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Xmx1G $SERVICE_OPTS"
    if [ "$SKIP_SCHEMA_INIT" = "false" ]; then
      if ! "$HIVE_HOME"/bin/schematool -dbType postgres -info; then
        initialize_hive
      fi
    fi

    if [ "$SERVICE_NAME" = "hiveserver2" ]; then
      export HADOOP_CLASSPATH="$TEZ_HOME"/*:"$TEZ_HOME"/lib/*:"$HADOOP_CLASSPATH"
    elif [ "$SERVICE_NAME" = "metastore" ]; then
      export METASTORE_PORT="${METASTORE_PORT:-9083}"
    fi

    exec "$HIVE_HOME"/bin/hive --skiphadoopversion --skiphbasecp --service "$SERVICE_NAME"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
  namespace: lakehouse
data:
  spark-defaults.conf: |
    spark.jars.packages=io.delta:delta-core_2.12:2.4.0,org.apache.hadoop:hadoop-aws:3.3.6
    spark.sql.extensions = io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog = org.apache.spark.sql.delta.catalog.DeltaCatalog
    spark.sql.warehouse.dir = s3a://wba/warehouse
  hive-site.xml: |
    <configuration>
        <property>
            <name>hive.metastore.uris</name>
            <value>thrift://hive-metastore:9083</value>
            <description>Thrift URI for remote metastore.</description>
        </property>
        <property>
            <name>fs.defaultFS</name>
            <value>s3a://wba</value>
        </property>
        <property>
            <name>fs.s3a.impl</name>
            <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
        </property>
        <property>
            <name>fs.s3a.connection.ssl.enabled</name>
            <value>false</value>
        </property>
        <property>
            <name>fs.s3a.aws.credentials.provider</name>
            <value>org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider</value>
        </property>
        <property>
            <name>fs.s3a.access.key</name>
            <value>${env:MINIO_ROOT_USER}</value>
        </property>
        <property>
            <name>fs.s3a.secret.key</name>
            <value>${env:MINIO_ROOT_PASSWORD}</value>
        </property>
        <property>
            <name>fs.s3a.endpoint</name>
            <value>http://minio:9000</value>
        </property>
        <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
        </property>
    </configuration>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kyuubi-config
  namespace: lakehouse
data:
  kyuubi-defaults.conf: |
    spark.hive.metastore.uris=thrift://hive-metastore:9083
    spark.master=spark://spark-master:7077
    spark.sql.adaptive.enabled=true
    spark.jars.packages=io.delta:delta-core_2.12:2.4.0,org.apache.hadoop:hadoop-aws:3.3.6,org.apache.hadoop:hadoop-common:3.3.6,org.apache.kyuubi:kyuubi-spark-sql-engine_2.12:1.8.0
    spark.sql.extensions = io.delta.sql.DeltaSparkSessionExtension
    spark.sql.catalog.spark_catalog = org.apache.spark.sql.delta.catalog.DeltaCatalog
    spark.hadoop.fs.defaultFS = s3a://wba
    spark.hadoop.fs.s3a.impl = org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.connection.ssl.enabled = false
    spark.hadoop.fs.s3a.aws.credentials.provider = org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    spark.hadoop.fs.s3a.access.key = ${env:MINIO_ROOT_USER}
    spark.hadoop.fs.s3a.secret.key = ${env:MINIO_ROOT_PASSWORD}
    spark.hadoop.fs.s3a.endpoint = http://minio:9000
    spark.hadoop.fs.s3a.path.style.access = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-apps
  namespace: lakehouse
data:
  csv_to_delta.py: |
    from delta.tables import DeltaTable
    from pyspark.sql import SparkSession


    def main():
        source_bucket = "wba"

        spark = (
            SparkSession.builder
            .appName("CSV File to Delta Lake Table")
            .enableHiveSupport()
            .getOrCreate()
        )

        input_path = f"s3a://{source_bucket}/test-data/people-100.csv"
        delta_base_path = f"s3a://{source_bucket}/delta/wba/tables/"

        spark.sql("DROP SCHEMA IF EXISTS wba CASCADE")
        spark.sql("CREATE DATABASE IF NOT EXISTS wba")
        spark.sql("USE wba")

        df = spark.read.csv(input_path, header=True, inferSchema=True)
        df.show()

        (
            df.write.format("delta")
            .option("delta.columnMapping.mode", "name")
            .option("path", f"{delta_base_path}/test_table")
            .saveAsTable("wba.test_table")
        )

        dt = DeltaTable.forName(spark, "wba.test_table")
        dt.toDF().show()


    if __name__ == "__main__":
        main()
